# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1eba9b2915737cfa9fbebe91c2a47a515c377dea2d41ec65fa5ea14355e5410e7715f5f85c8722d49e6a6792d7a345c23b2c9cb011796a27e87739c16998dbd6

test:
  secret_key_base: e8d86fd6afff0281d2664ad6e92007a0764e4b045b4dfd6dbae8dcec6476ce1379656be6e6e1a650e0dd553be783b6a6a7957170c6a2e811e63b1b4dd745f761

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
